export const CITIES = [
  {
    name: 'New Delhi',
    latitude: 28.6139,
    longitude: 77.209,
    code: 'DEL',
    flag: '🇮🇳',
    country: 'India',
  },
  {
    name: 'New York',
    latitude: 40.7128,
    longitude: -74.006,
    code: 'NYC',
    flag: '🇺🇸',
    country: 'USA',
  },
  {
    name: 'Paris',
    latitude: 48.8566,
    longitude: 2.3522,
    code: 'PAR',
    flag: '🇫🇷',
    country: 'France',
  },
  {
    name: 'Tokyo',
    latitude: 35.6895,
    longitude: 139.6917,
    code: 'TYO',
    flag: '🇯🇵',
    country: 'Japan',
  },
  {
    name: 'Sydney',
    latitude: -33.8688,
    longitude: 151.2093,
    code: 'SYD',
    flag: '🇦🇺',
    country: 'Australia',
  },
  {
    name: 'London',
    latitude: 51.5074,
    longitude: -0.1278,
    code: 'LON',
    flag: '🇬🇧',
    country: 'United Kingdom',
  },
  {
    name: 'Dubai',
    latitude: 25.276987,
    longitude: 55.296249,
    code: 'DXB',
    flag: '🇦🇪',
    country: 'UAE',
  },
  {
    name: 'Cape Town',
    latitude: -33.9249,
    longitude: 18.4241,
    code: 'CPT',
    flag: '🇿🇦',
    country: 'South Africa',
  },
];
