export const CITIES = [
  {
    name: 'New Delhi',
    latitude: 28.6139,
    longitude: 77.209,
    code: 'DEL',
    flag: '🇮🇳',
    country: 'India',
    textColor: 'white',
  },
  {
    name: 'New York',
    latitude: 40.7128,
    longitude: -74.006,
    code: 'NYC',
    flag: '🇺🇸',
    country: 'USA',
    textColor: 'white',
  },
  {
    name: 'Paris',
    latitude: 48.8566,
    longitude: 2.3522,
    code: 'PAR',
    flag: '🇫🇷',
    country: 'France',
    textColor: 'black',
  },
  {
    name: 'Tokyo',
    latitude: 35.6895,
    longitude: 139.6917,
    code: 'TYO',
    flag: '🇯🇵',
    country: 'Japan',
    textColor: 'black',
  },
  {
    name: 'Sydney',
    latitude: -33.8688,
    longitude: 151.2093,
    code: 'SYD',
    flag: '🇦🇺',
    country: 'Australia',
    textColor: 'black',
  },
  {
    name: 'London',
    latitude: 51.5074,
    longitude: -0.1278,
    code: 'LON',
    flag: '🇬🇧',
    country: 'United Kingdom',
    textColor: 'black',
  },
  {
    name: 'Dubai',
    latitude: 25.276987,
    longitude: 55.296249,
    code: 'DXB',
    flag: '🇦🇪',
    country: 'UAE',
    textColor: 'black',
  },
  {
    name: 'Cape Town',
    latitude: -33.9249,
    longitude: 18.4241,
    code: 'CPT',
    flag: '🇿🇦',
    country: 'South Africa',
    textColor: 'black',
  },
];

export const themeColors = {
  light: [
    '#FFA07A',
    '#9370DB',
    '#B0C4DE',
    '#D3D3D3',
    '#FFB6C1',
    '#98FB98',
    '#FFDAB9',
    '#E6E6FA',
  ],
  dark: [
    '#FF7F50',
    '#7A5C9B',
    '#8A9BB6',
    '#A9A9A9',
    '#FF69B4',
    '#66CDAA',
    '#FFB6A0',
    '#B0A0D9',
  ],
};
